#!/bin/bash
{ printf "%s\n" . .. $(LC_ALL=C find . -maxdepth 1 -type d -name '[0-9A-Za-z]*' -printf '%f/') $(LC_ALL=C find . -maxdepth 1 -type f -o -type d -name '.*' -printf '%f'); echo; } | tr -d '\n'

